version: '3.8'

services:
  logger-db:
    build: ./mongo/
    restart: always
    ports:
      - 27017:27017
    volumes:
      - log-data:/data/db
    env_file:
      - ./config/mongod.env

volumes:
  log-data: {}

# networks:

    