version: '3.8'

services:
  db: # both development and production
    container_name: general-bot-database
    build: ./mongo/
    restart: always
    ports:
      - 27017:27017
    volumes:
      - bot-data:/data/db
    env_file:
      - ./config/mongod.env
      - ./config/bot.env

  dev-bot:
    container_name: general-bot-main-development
    depends_on:
      - db
    image: rust:1.67
    ports:
      - 8080:8080
    volumes:
      - ./bot:/usr/src/bot
    working_dir: /usr/src/bot
    env_file:
      - ./config/bot.env
    command: ["cargo", "run"]

  dev-api:
    container_name: general-bot-api-development
    depends_on:
      - db
    image: node:19
    ports:
      - 8081:8081
    volumes:
      - ./api:/home/node/app
    working_dir: /home/node/app
    env_file:
      - ./config/api.env
    command: ["npm", "run", "dev"]


  bot:
    container_name: general-bot-main
    depends_on:
      - db
    build: ./bot/
    restart: always
    volumes:
      - ./bot:/usr/src/bot
    env_file:
      - ./config/bot.env

volumes:
  bot-data: {}


    