version: '3.8'

services:
  db:
    build: ./mongo/
    restart: always
    ports:
      - 27017:27017
    volumes:
      - bot-data:/data/db
    env_file:
      - ./config/mongod.env
      - ./config/bot.env

volumes:
  bot-data: {}

# networks:

    